App({
  // 全局变量
  globalData: {
    classlist:[
      {
        cart_id:1,
        cart_name: '产妇专区',
        ishaveChild: true,
        children:{
          '1001':
          {
            item_id: 1001,
            name:'会阴冷敷垫',
            price: 65,
            oldprice: 90,
            count:1,
            buyRate: 0,
            image: "/previewImage/1001.jpg",
            imgUrls:["/previewImage/1001/slides/1.jpg"],
            detailUrls:["/previewImage/1001/details/2.jpg","/previewImage/1001/details/3.jpg","/previewImage/1001/details/4.jpg","/previewImage/1001/details/5.jpg"],
          },
          '1002':
          {
            item_id: 1002,
            name:'乳头吸引器',
            price: 25,
            oldprice: 40,
            count:1,
            buyRate: 0,
            image: "/previewImage/1002.jpg",
            imgUrls:["/previewImage/1002/slides/1.jpg"],
            detailUrls:["/previewImage/1002/details/2.jpg","/previewImage/1002/details/3.jpg","/previewImage/1002/details/4.jpg","/previewImage/1002/details/5.jpg"],
          },
          '1003':
          {
            item_id: 1003,
            name:'胎监带',
            price: 63,
            oldprice: 75,
            count:1,
            buyRate: 0,
            image: "/previewImage/1003.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '1004':
          {
            item_id: 1004,
            name:'防水创可贴',
            price: 12,
            oldprice: 25,
            count:1,
            buyRate: 0,
            image: "/previewImage/1004.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '1005':
          {
            item_id: 1005,
            name:'腹带',
            price: 27,
            oldprice: 50,
            count:1,
            buyRate: 0,
            image: "/previewImage/1005.jpg",
            imgUrls:[],
            detailUrls:[],
          }
        },
      },
      {
        cart_id: 2,
        cart_name: '宝宝专区',
        ishaveChild: true,
        children:{
          '2001':{
            item_id: 2001,
            name:'婴儿喂勺',
            price: 20,
            oldprice: 28,
            count:1,
            buyRate: 0,
            image: "/previewImage/2001.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '2002':{
            item_id: 2002,
            name:'婴儿喂杯',
            price: 60,
            oldprice: 77,
            count:1,
            buyRate: 0,
            image: "/previewImage/2002.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '2003':{
            item_id: 2003,
            name:'护脐带',
            price: 40,
            oldprice: 66,
            count:1,
            buyRate: 0,
            image: "/previewImage/2003.jpg",
            imgUrls:[],
            detailUrls:[],
          },
        }
      },
      {
        cart_id: 3,
        cart_name: '护理专区',
        ishaveChild: true,
        children:{
        '3001':{
            item_id: 3001,
            name:'一次性马桶垫',
            price: 25,
            oldprice: 30,
            count:1,
            buyRate: 0,
            image: "/previewImage/3001.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '3002':{
            item_id: 3002,
            name:'一次性全棉内裤',
            price: 12,
            oldprice: 19,
            count:1,
            buyRate: 0,
            image: "/previewImage/3002.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '3003':{
            item_id: 3003,
            name:'医用检查垫',
            price: 22,
            oldprice: 27,
            count:1,
            buyRate: 0,
            image: "/previewImage/3003.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '3004':{
            item_id: 3004,
            name:'医用护理垫',
            price: 31,
            oldprice: 39,
            count:1,
            buyRate: 0,
            image: "/previewImage/3004.jpg",
            imgUrls:[],
            detailUrls:[],
          },
          '3005':{
            item_id: 3005,
            name:'产妇垫',
            price: 29,
            oldprice: 40,
            count:1,
            buyRate: 0,
            image: "/previewImage/3005.jpg",
            imgUrls:[],
            detailUrls:[],
          },
        }
      }
    ]
  },
})